"""Shared pytest fixtures."""

import os
import sys
import types
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

# ── Environment setup (must happen before any app imports) ─────────────────────
TEST_DATABASE_URL = "sqlite:////tmp/test_rag.db"
os.environ.setdefault("DATABASE_URL", TEST_DATABASE_URL)
os.environ.setdefault("NVIDIA_API_KEY", "test_key")
os.environ.setdefault("FAISS_INDEX_PATH", "/tmp/test_faiss_index")
os.environ.setdefault("UPLOAD_DIR", "/tmp/test_uploads")
os.environ.setdefault("MLFLOW_TRACKING_URI", "/tmp/test_mlruns")

# ── Stub out sentence_transformers so torch is NOT required ────────────────────
def _make_stub_sentence_transformers():
    """Return a minimal stub for sentence_transformers."""
    module = types.ModuleType("sentence_transformers")

    class _FakeSentenceTransformer:
        def __init__(self, model_name_or_path, *args, **kwargs):
            self._dim = 384

        def get_sentence_embedding_dimension(self):
            return self._dim

        def encode(self, sentences, batch_size=64, show_progress_bar=False,
                   convert_to_numpy=True, normalize_embeddings=True, **kwargs):
            rng = np.random.default_rng(0)
            n = len(sentences) if isinstance(sentences, list) else 1
            vecs = rng.random((n, self._dim)).astype(np.float32)
            norms = np.linalg.norm(vecs, axis=1, keepdims=True)
            return (vecs / norms)

    module.SentenceTransformer = _FakeSentenceTransformer
    return module


if "sentence_transformers" not in sys.modules:
    sys.modules["sentence_transformers"] = _make_stub_sentence_transformers()

# ── Stub out MLflow so network calls don't happen in tests ────────────────────
if "mlflow" not in sys.modules:
    mlflow_stub = types.ModuleType("mlflow")
    mlflow_stub.set_tracking_uri = lambda *a, **k: None
    mlflow_stub.set_experiment = lambda *a, **k: None
    mlflow_stub.set_tag = lambda *a, **k: None
    mlflow_stub.log_param = lambda *a, **k: None
    mlflow_stub.log_metric = lambda *a, **k: None
    ctx = MagicMock()
    ctx.__enter__ = lambda s: s
    ctx.__exit__ = lambda *a: False
    mlflow_stub.start_run = lambda **k: ctx
    sys.modules["mlflow"] = mlflow_stub

# ── Now safe to import app ─────────────────────────────────────────────────────
from sqlalchemy import create_engine  # noqa: E402
from sqlalchemy.orm import sessionmaker, Session  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from app.database.connection import Base, get_db  # noqa: E402
from app.main import app  # noqa: E402


# ── DB fixtures ────────────────────────────────────────────────────────────────
@pytest.fixture(scope="session")
def test_engine():
    engine = create_engine(TEST_DATABASE_URL, connect_args={"check_same_thread": False})
    Base.metadata.create_all(bind=engine)
    yield engine
    Base.metadata.drop_all(bind=engine)
    Path("/tmp/test_rag.db").unlink(missing_ok=True)


@pytest.fixture
def db_session(test_engine) -> Generator[Session, None, None]:
    LocalSession = sessionmaker(autocommit=False, autoflush=False, bind=test_engine)
    session = LocalSession()
    try:
        yield session
    finally:
        session.rollback()
        session.close()


# ── HTTP client fixture ────────────────────────────────────────────────────────
@pytest.fixture
def client(db_session: Session) -> Generator:
    """FastAPI test client with overridden DB and mocked LLM."""
    import app.api.routes as _routes
    from unittest.mock import MagicMock

    # Reset module-level singletons so each test starts fresh
    _routes._pipeline = None
    _routes._generator = None

    def override_get_db():
        yield db_session

    # Build a fully mocked LLMClient so no real HTTP client (or SOCKS proxy) is created
    mock_llm = MagicMock()
    mock_llm.model = "mock-model"
    mock_llm.generate.return_value = (
        "This is a test answer generated by the mocked LLM.",
        0.05,
    )

    app.dependency_overrides[get_db] = override_get_db

    with patch("app.api.routes.LLMClient", return_value=mock_llm):
        with TestClient(app) as c:
            yield c

    app.dependency_overrides.clear()
    # Reset singletons after test too
    _routes._pipeline = None
    _routes._generator = None


# ── File fixtures ──────────────────────────────────────────────────────────────
@pytest.fixture
def sample_txt_file(tmp_path: Path) -> Path:
    content = (
        "Artificial intelligence is the simulation of human intelligence processes "
        "by machines, especially computer systems.\n\n"
        "Machine learning is a subset of AI that enables systems to learn and improve "
        "from experience without being explicitly programmed.\n\n"
        "Deep learning uses neural networks with many layers to analyse various factors "
        "of data, including images, audio, and text.\n"
    )
    txt = tmp_path / "sample.txt"
    txt.write_text(content)
    return txt


@pytest.fixture
def sample_pdf_file(tmp_path: Path) -> Path:
    from pypdf import PdfWriter
    writer = PdfWriter()
    writer.add_blank_page(width=612, height=792)
    dest = tmp_path / "sample.pdf"
    with dest.open("wb") as f:
        writer.write(f)
    return dest
